# Generated by Django 4.0.3 on 2022-03-25 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='aiondj/uploads/produtos/')),
                ('preco_unitario', models.IntegerField(default=0)),
                ('estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('cpf', models.CharField(blank=True, default='', max_length=11)),
                ('nome', models.CharField(blank=True, default='', max_length=50)),
                ('endereco', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produtos')),
            ],
        ),
    ]
